upgrade zmq to 4.3.1

diff --git a/dev/lifecycle/sec b/dev/lifecycle/sec
--- a/dev/lifecycle/sec
+++ b/dev/lifecycle/sec
@@ -3,31 +3,35 @@
 set -eu
 trap exit INT TERM
 
-TARGET_PACKAGE=""
+################################################################################
 
+SOURCE=""
 while [ $# -gt 0 ] ; do
 key="$1"
-
 case $key in
-
-  --pkg)
-    TARGET_PACKAGE="$2"
-    shift
-    shift
-  ;;
-
-  *)
-    shift
-  ;;
-
+  --source)  SOURCE="$2";  shift; shift; ;;
+  *)                       shift;        ;;
 esac
 done
 
-if [ ! "${TARGET_PACKAGE}" ] ; then
-  (>&2 echo "[error] target package not provided")
+################################################################################
+
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "[error] source package not provided")
   exit 1
 fi
 
-cd /go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
+################################################################################
 
-gosec ./...
+lifecycle::go::sec() {
+  local dir="$1"
+  if [ -z ${dir} -o ! -d ${dir} ] ; then
+    return
+  fi
+  cd ${dir} && gosec -exclude=G104,G302 ./...
+}
+
+################################################################################
+
+lifecycle::go::sec \
+  ${SOURCE}
diff --git a/dev/lifecycle/test b/dev/lifecycle/test
--- a/dev/lifecycle/test
+++ b/dev/lifecycle/test
@@ -3,63 +3,80 @@
 set -e
 trap exit INT TERM
 
-TARGET_PACKAGE=""
+################################################################################
 
+SOURCE=""
+OUTPUT=""
 while [ $# -gt 0 ] ; do
 key="$1"
-
 case $key in
-
-  --pkg)
-    TARGET_PACKAGE="$2"
-    shift
-    shift
-  ;;
-
-  *)
-    shift
-  ;;
-
+  --source) SOURCE="$2";  shift; shift; ;;
+  --output) OUTPUT="$2";  shift; shift; ;;
+  *)                      shift;        ;;
 esac
 done
 
-if [ ! "${TARGET_PACKAGE}" ] ; then
-  (>&2 echo "[error] target package not provided")
+################################################################################
+
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "[error] source package not provided")
   exit 1
 fi
 
-coverage_out=$(tempfile)
-test_out=$(tempfile)
-reports_out=$(pwd)/reports
+if [ -z "${OUTPUT}" ] ; then
+  (>&2 echo "[error] output not provided")
+  exit 1
+fi
 
-mkdir -p ${reports_out} ${reports_out}/unit-tests-${TARGET_PACKAGE}
+################################################################################
 
-cd /go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
+lifecycle::go::test() {
+  local dir="$1"
+  if [ -z ${dir} -o ! -d ${dir} ] ; then
+    return
+  fi
+  local output="$2"
+  local target=$(basename $dir)
 
-# run unit tests and collect coverage
+  coverage_out=$(tempfile)
+  test_out=$(tempfile)
 
-2>&1 \
+  mkdir -p ${output}
+
+  # run unit tests and collect coverage
+  cd ${dir} && \
+  \
+  GOMAXPROCS=1 \
   go test \
-  -v ./... \
-  -coverprofile=${coverage_out} \
-  -coverpkg=./... \
-  -timeout=20s | tee ${test_out}
+    -v ./... \
+    -coverprofile=${coverage_out} \
+    -coverpkg=./... \
+    -timeout=10s \
+  | grc tee ${test_out}
 
-go2xunit \
-  -fail \
-  -input ${test_out} \
-  -output ${reports_out}/unit-tests-${TARGET_PACKAGE}/results.xml
+  go2xunit \
+    -fail \
+    -input ${test_out} \
+    -output ${output}/${target}-results.xml
 
-go tool cover \
-  --html=${coverage_out} \
-  -o ${reports_out}/unit-tests-${TARGET_PACKAGE}/coverage.html
+  go tool cover \
+    --html=${coverage_out} \
+    -o ${output}/${target}-coverage.html
 
-# run only benchmarks
+  # run only benchmarks
+  cd ${dir} && \
+  \
+  GOMAXPROCS=1 \
+    grc go test \
+    -v ./... \
+    -run=^$ \
+    -bench=. \
+    -benchmem \
+    -timeout=1m
+}
 
-GOMAXPROCS=1 \
-  go test \
-  -v ./... \
-  -run=^$ \
-  -bench=. \
-  -benchmem \
-  -timeout=1m
+################################################################################
+
+lifecycle::go::test \
+  ${SOURCE} \
+  ${OUTPUT}
